#!/bin/bash
#$ -N DownloadPATRIC 
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -cwd
#$ -l h_data=4G
#$ -l time=12:00:00
#$ -m bea

genome_ids=`cat ~/mother_infant/midas_db_v1.2/genome_info.txt | cut -f1 | tail -n +2`

for i in $genome_ids
do
	wget -qN "ftp://ftp.patricbrc.org/genomes/$i/$i.features.tab";
done
