#!/bin/bash
#$ -N postprocess_core_genes_MegaMI
#$ -cwd
#$ -e /u/project/ngarud/daisyche/mother_infant/logs/ACTUALFINAL
#$ -o /u/project/ngarud/daisyche/mother_infant/logs/ACTUALFINAL
#$ -l h_data=32G
#$ -l highp
#$ -l time=100:00:00
#$ -m a

. /u/local/Modules/default/init/modules.sh
module load python/2.7

ppdir=/u/project/ngarud/daisyche/mother_infant/scripts/postprocess

echo 'Calculating core genes...'
python $ppdir/postprocess/calculate_core_genes.py nonpremie
echo 'Done claculating core genes!'
