#!/bin/bash
#$ -N temp_change_hmp_MegaMI
#$ -cwd
#$ -e /u/project/ngarud/daisyche/mother_infant/logs/final2
#$ -o /u/project/ngarud/daisyche/mother_infant/logs/final2
#$ -l h_data=80G
#$ -l highp
#$ -l time=22:00:00
#$ -t 1-4 # skip 412 for now which is Providencia_rettgeri_61888
#$ -m a

. /u/local/Modules/default/init/modules.sh
module load python/2.7

ppdir=/u/project/ngarud/daisyche/mother_infant/scripts/postprocess

readarray all_species < /u/project/ngarud/daisyche/mother_infant/data/pickles/species_list.txt
all_species=(null ${all_species[@]}) # zero to one start index
species=${all_species[$SGE_TASK_ID]}

python $ppdir/calculate_temporal_changes.py $species --prev_cohort hmp
echo Done postprocessing temporal changes for $species
