#!/bin/bash
#$ -N postprocess_sfs_MegaMI
#$ -cwd
#$ -e /u/project/ngarud/daisyche/mother_infant/logs/
#$ -o /u/project/ngarud/daisyche/mother_infant/logs/
#$ -l h_data=32G
#$ -l time=23:00:00
#$ -t 1-411 # skip 412 for now which is Providencia_rettgeri_61888
#$ -m e

. /u/local/Modules/default/init/modules.sh
module load python/2.7

ppdir=/u/project/ngarud/daisyche/mother_infant/scripts/postprocess

readarray all_species < /u/project/ngarud/daisyche/mother_infant/data/pickles/species_list.txt
all_species=(null ${all_species[@]}) # zero to one start index
species=${all_species[$SGE_TASK_ID]}

echo Postprocessing species $species

# Calculate substitution rates

echo 'Calculating within person SFS...'
python $ppdir/calculate_within_person_sfs.py $species
echo 'Done calculating within person SFS!'

