#!/bin/bash
#$ -N temporal_changes_MegaMI
#$ -cwd
#$ -e /u/project/ngarud/daisyche/mother_infant/logs/ACTUALFINAL
#$ -o /u/project/ngarud/daisyche/mother_infant/logs/ACTUALFINAL
#$ -l h_data=16G
#$ -l highp
#$ -l time=30:00:00
#$ -t 41-502 # skip 412 for now which is Providencia_rettgeri_61888
#$ -m a

. /u/local/Modules/default/init/modules.sh
module load python/2.7

ppdir=/u/project/ngarud/daisyche/mother_infant/scripts/postprocess

readarray all_species < /u/project/ngarud/daisyche/mother_infant/data/pickles/species_list.txt
all_species=(null ${all_species[@]}) # zero to one start index
species=${all_species[$SGE_TASK_ID]}

echo Postprocessing species $species

echo 'Calculating subs rates with cohorts hmp, infant, all...'
python $ppdir/calculate_temporal_changes.py $species --prev_cohort all --min_coverage 0
python $ppdir/calculate_temporal_changes.py $species --prev_cohort hmp --min_coverage 0
python $ppdir/calculate_temporal_changes.py $species --prev_cohort infant --min_coverage 0
echo 'Done'

# Calculate within person SFS
# this produces within_sample_sfs.txt.bz2. 
# cohort options: all, infant, hmp, mother
# echo 'Calculating within-sample SFSs...'
# python $ppdir/calculate_within_person_sfs.py $species --cohort hmp
# python $ppdir/calculate_within_person_sfs.py $species --cohort infant
# python $ppdir/calculate_within_person_sfs.py $species --cohort all
# python $ppdir/calculate_within_person_sfs.py $species --cohort mother
# echo 'Done calculating coverage distribution!'
