#!/bin/bash
#$ -N seeding
#$ -e /u/project/ngarud/daisyche/mother_infant/logs/seeding
#$ -o /u/project/ngarud/daisyche/mother_infant/logs/seeding
#$ -l highp
#$ -l h_data=32G
#$ -l time=20:00:00
#$ -t 1-20

. /u/local/Modules/default/init/modules.sh
module load python/2.7

sdir=/u/project/ngarud/daisyche/mother_infant/scripts

readarray all_species < /u/project/ngarud/daisyche/mother_infant/data_latest/pickles/good_species_list.txt
all_species=(null ${all_species[@]}) # zero to one start index
species=${all_species[$SGE_TASK_ID]}

echo Postprocessing species $species

python $sdir/pickle_mom_seeding.py $species
