#!/bin/bash
#$ -N gene_changes_anno_old
#$ -cwd
#$ -e /u/project/ngarud/daisyche/mother_infant/logs/final
#$ -o /u/project/ngarud/daisyche/mother_infant/logs/final
#$ -l h_data=32G
#$ -l time=22:00:00
#$ -t 1-49

. /u/local/Modules/default/init/modules.sh
module load python/2.7

sdir=/u/project/ngarud/daisyche/mother_infant/scripts

readarray all_species < /u/project/ngarud/daisyche/mother_infant/data/pickles/species_list.txt
all_species=(null ${all_species[@]}) # zero to one start index
species=${all_species[$SGE_TASK_ID]}

echo Postprocessing species $species

python $sdir/gene_changes_annotation_old.py $species
