#!/bin/bash
#$ -N PickleEverything
#$ -e /u/project/ngarud/daisyche/mother_infant/logs/ACTUALFINAL
#$ -o /u/project/ngarud/daisyche/mother_infant/logs/ACTUALFINAL
#$ -cwd
#$ -l h_data=32G
#$ -l highp
#$ -l time=100:00:00
#$ -m ea

. /u/local/Modules/default/init/modules.sh
module load python/2.7

# Run the script!

python ~/mother_infant/scripts/pickle_everything.py

# python ~/mother_infant/scripts/postprocess/calculate_core_genes.py hmp
# python ~/mother_infant/scripts/snp_freq_changes.py 20
# python ~/mother_infant/scripts/pickle_snp_changes.py full
# python ~/mother_infant/scripts/pickle_prevalence_plot.py full
# python ~/mother_infant/scripts/pickle_dnds.py full
# python ~/mother_infant/scripts/pickle_pnps.py rare
# python ~/mother_infant/scripts/pickle_pnps.py common

# python ~/mother_infant/scripts/postprocess/calculate_core_genes.py
# python ~/mother_infant/scripts/pickle_snp_changes_sites.py full

# python ~/mother_infant/scripts/pickle_reversions.py full

# python ~/mother_infant/scripts/diversity_vs_snp_changes.py --sweep-type partial

# python ~/mother_infant/scripts/diversity_vs_snp_changes.py --sweep-type full

