#!/bin/bash
#$ -N postprocess_error_MegaMI
#$ -cwd
#$ -e /u/project/ngarud/daisyche/mother_infant/logs/postproc_logs
#$ -o /u/project/ngarud/daisyche/mother_infant/logs/postproc_logs
#$ -l h_data=16G
#$ -l highp
#$ -l time=330:00:00
#$ -t 2-2 # skip 412 for now which is Providencia_rettgeri_61888
#$ -m e

. /u/local/Modules/default/init/modules.sh
module load python/2.7

ppdir=/u/project/ngarud/daisyche/mother_infant/scripts/postprocess

readarray all_species < /u/project/ngarud/daisyche/mother_infant/data/pickles/species_list.txt
all_species=(null ${all_species[@]}) # zero to one start index
species=${all_species[$SGE_TASK_ID]}

echo Postprocessing species $species

# Calculate error pvalues
# this produces the file annotated_snps.txt.bz2, which contains SNPs that fall between 0.3*median and 3*median,
# where median=median coverage of a SNP in a sample. The output is in the form of Alt, Ref, where Ref=consensus
# allele across samples (so, the output is polarized relative to the major allele in the sample).

echo 'Calculating error pvalues...'
python $ppdir/calculate_error_pvalues.py $species
echo 'Done calculating error pvalues!'
