#!/bin/bash

echo Postprocessing species $species

# core genes

echo 'Calculating core genes...'
python calculate_core_genes.py
echo 'Done calculating core genes!'

# the following creates this file: marker_coverage.txt.bz2
# It consists of a line recapitulating MIDAS output in terms of coverage for the species of interest
# It also outputs a line summing over the coverage across all species for each sample.

echo 'Calculating marker gene coverages...'
python calculate_marker_gene_coverage.py
echo 'Done calculating marker gene coverages!'

# the following step outputs three files:
# 1) coverage distribution for each sample without respect to prevalence of a site (full_coverage_distribution.txt.bz2)
# 2) coverage distribution for each sample with respect to prevalence (coverage_distribution.txt.bz2)
# 3) coverage distribution for each gene x sample using the reads from the SNPs output (gene_coverage.txt.bz2)

echo 'Calculating coverage distributions...'
python calculate_coverage_distribution.py
echo 'Done calculating coverage distribution!'

# Calculate error pvalues
# this produces the file annotated_snps.txt.bz2, which contains SNPs that fall between 0.3*median and 3*median, where median=median coverage of a SNP in a sample. The output is in the form of Alt, Ref, where Ref=consensus allele across samples (so, the output is polarized relative to the major allele in the sample). 
echo 'Calculating error pvalues...'
python calculate_error_pvalues.py
echo 'Done calculating error pvalues!'

# Calculate snp prevalences
# this produces a list in snp_prevalences/ directory to be loaded later
# (can disable this and supply the list externally.)
echo 'Calculating SNP prevalences...'
python calculate_snp_prevalences.py
echo 'Done calculating SNP prevalences!'

# Calculate within person SFS
# this produces within_sample_sfs.txt.bz2. 
echo 'Calculating within-sample SFSs...'
python calculate_within_person_sfs.py
echo 'Done calculating within-sample SFSs!'

# Calculate substitution rates between samples
echo 'Calculating substitution rates...'
python calculate_substitution_rates.py
echo 'Done calculating substitution rates!'

# Calculate singleton substitution rates
echo 'Calculating singleton rates...'
python calculate_singletons.py
echo 'Done calculating singleton rates!'

# Calculate private SNVs
echo 'Calculating private SNVs...'
python calculate_private_snvs.py
echo 'Done calculating private SNVs!'

# Calculate temporal changes
echo 'Calculating temporal changes...'
python calculate_temporal_changes.py
echo 'Done calculating temporal changes!'

# Calculate SNV inconsistency (for recombination figure
echo 'Calculating SNV inconsistency...'
python calculate_snv_distances.py --species
echo 'Done calculating SNV inconsistency!'

# Calculating linkage disequilibrium inconsistency (for recombination figure
echo 'Calculating LD...'
python calculate_linkage_disequilibria.py --species
echo 'Done calculating LD!'
   
echo Done postprocessing $species
