#!/bin/bash      
#$ -N TemporalChangeTest
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -cwd
#$ -l h_data=4G
#$ -l time=08:00:00
#$ -m bea

. /u/local/Modules/default/init/modules.sh
module load python/2.7

python ~/mother_infant/scripts/calculate_temporal_changes.py 'Bacteroides_uniformis_57318'

python ~/mother_infant/scripts/calculate_temporal_changes.py 'Bacteroides_vulgatus_57955'
