#!/bin/bash
#$ -N TempChangePlot
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -cwd
#$ -l h_data=4G
#$ -l time=02:00:00
#$ -m e

. /u/local/Modules/default/init/modules.sh
module load python/2.7

# Run the plot script!
python ~/mother_infant/scripts/plot_snv_changes_prev.py --sweep_type partial
