#!/bin/bash
#$ -N OlmMIDASspecies
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -cwd
#$ -r y
#$ -j y
#$ -l h_data=20G
#$ -l time=23:00:00
#$ -tc 100 # Throttle to max 100 tasks at a time
#$ -t 1-949

. /u/local/Modules/default/init/modules.sh
module load python/2.7

export PYTHONPATH=$PYTHONPATH:/u/project/ngarud/Garud_lab/MIDAS
export PATH=$PATH:/u/project/ngarud/Garud_lab/MIDAS/scripts
export MIDAS_DB=/u/project/ngarud/Garud_lab/midas_db_v1.2

readarray accs < /u/project/ngarud/Garud_lab/metagenomic_fastq_files/Olm_2019/Olm_run_accession_only.txt
accs=(null ${accs[@]}) # zero to one start index
acc=${accs[$SGE_TASK_ID]}
echo $acc

OUTDIR=/u/project/ngarud/Garud_lab/metagenomic_fastq_files/Olm_2019/midas_output/${acc}

mkdir $OUTDIR

fastq1=/u/project/ngarud/Garud_lab/metagenomic_fastq_files/Olm_2019/converted_fastq_files/${acc}_1.fastq.gz
fastq2=/u/project/ngarud/Garud_lab/metagenomic_fastq_files/Olm_2019/converted_fastq_files/${acc}_2.fastq.gz

if [ ! -f $fastq2 ] # Single end
then run_midas.py species $OUTDIR -1 $fastq1
else run_midas.py species $OUTDIR -1 $fastq1 -2 $fastq2
fi

