#!/bin/bash
#$ -N PrevPlots
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -cwd
#$ -l h_data=4G
#$ -l time=02:00:00
#$ -t 1-36
#$ -m e

. /u/local/Modules/default/init/modules.sh
module load python/2.7

numfields=5

# Don't use this for now, too much and redundant
: 'prev_cohorts='all infant hmp'
within_host_types='consecutive longest nonconsecutive'
within_mi_pair_types='first last random all'
sweep_types='full partial'

param_list=()

for sweep_type in $sweep_types
do
	for prev_cohort in $prev_cohorts
	do
		for within_host_type in $within_host_types
		do
			for within_mi_pair_type in $within_mi_pair_types
			do
				param_list+=($sweep_type)
				param_list+=($prev_cohort)
				param_list+=($within_host_type)
				param_list+=($within_mi_pair_type)
			done
		done
	done
done'

# Manually constructed parameter list
# The order is: prevalence cohort, within_host_type, within_mi_pair_type, sweep_type
readarray param_list < ~/mother_infant/tmp_intermediate_files/new_prev_parameter_list.txt

# Indices in parameter list corresponding to one task array entry
# Note, the first task ID is 1, must subtract 1 for indexing
mod_task_id=$(($SGE_TASK_ID - 1))
base_i=$(($numfields*$mod_task_id))
this_prev_cohort_i=$(($base_i))
this_within_host_type_i=$(($base_i + 1))
this_within_mi_pair_type_i=$(($base_i + 2))
this_sweep_type_i=$(($base_i + 3))
this_modification_threshold_i=$(($base_i + 4))

# Fill in parameters based on indices
this_prev_cohort=${param_list[$this_prev_cohort_i]}
this_within_host_type=${param_list[$this_within_host_type_i]}
this_within_mi_pair_type=${param_list[$this_within_mi_pair_type_i]}
this_sweep_type=${param_list[$this_sweep_type_i]}
this_modification_threshold=${param_list[$this_modification_threshold_i]}

# Run the plot script!
python ~/mother_infant/scripts/plot_snv_changes_prev.py --prevalence_cohort $this_prev_cohort --within_host_type $this_within_host_type --within_mi_pair_type $this_within_mi_pair_type --sweep_type $this_sweep_type --modification_threshold $this_modification_threshold
