#!/bin/bash
#$ -N BadGenes
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -cwd
#$ -l h_data=30G
#$ -l time=10:00:00
#$ -m e
#$ -t 1-123

. /u/local/Modules/default/init/modules.sh
module load python/2.7

readarray files < ~/mother_infant/tmp_intermediate_files/tmp_species_list.txt
files=(null ${files[@]}) # this pads the file with an extra line in the beginning.
species=${files[$SGE_TASK_ID]}
echo $species

# Run the plot script!

python ~/mother_infant/scripts/gene_changes_bad_genes.py --other-species $species 
