#!/bin/bash      
#$ -N ReTempChange4
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -cwd      
#$ -l h_data=4G
#$ -l time=12:00:00 
#$ -t 1-123
#$ -m e

. /u/local/Modules/default/init/modules.sh
module load python/2.7

readarray files < ~/mother_infant/tmp_intermediate_files/tmp_species_list.txt
files=(null ${files[@]}) # this pads the file with an extra line in the beginning.
species=${files[$SGE_TASK_ID]}
echo $species

python ~/mother_infant/scripts/calculate_temporal_changes.py $species
